### ISSUE TITLE
Error `TypeError: plugin.apply is not a function`

### ISSUE THREAD

**Issue by nhoizey** [boyum/markdown-it-image-size#402]
I'm trying to use `markdown-it-image-size` 13.1.1 with `markdown-it` 13.0.1 and I get this error, whatever code I write: `TypeError: plugin.apply is not a function`

This is a simple example:

```js
const MarkdownIt = require("markdown-it");
const MarkdownItImageSize = require("markdown-it-image-size");

const md = new MarkdownIt();
md.use(MarkdownItImageSize);

let result = md.render(`# markdown-it rulezz!

![](image.jpg)

`);

console.log(result);
```

Here's the error log:

```shell
node_modules/markdown-it/lib/index.js:497
  plugin.apply(plugin, args);
         ^

TypeError: plugin.apply is not a function
    at MarkdownIt.use (node_modules/markdown-it/lib/index.js:497:10)
    at Object.<anonymous> (index.js:5:4)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.1
```

**Comment by boyum** [comment]
Thanks for creating the issue! I'll look into it as soon as I have some free time ✨

**Comment by nhoizey** [comment]
Thanks! 🙏

**Comment by nhoizey** [comment]
@boyum I guess there's a typo in your code with a lowercase initial in `markdownItImageSize`.

But anyway, I get the same error with `{ MarkdownItImageSize } = require("markdown-it-image-size");` as I did without the curly braces.

**Comment by boyum** [comment]
No, the exported function is named `markdownItImageSize`, not `MarkdownItImageSize`.

**Comment by nhoizey** [comment]
But then you use `md.use(MarkdownItImageSize);` with an uppercase `M`? 🤔

**Comment by nhoizey** [comment]
Ooooh, it works when I use lowercase `m` everywhere… sorry for not trying it first. 😞

**Comment by boyum** [comment]
Ah, sorry for updating only the import, not inside `use`. Great!

**Comment by boyum** [comment]
@dingshaohua-cn Please continue this conversation in #416.
