### ISSUE TITLE
ESM Support

### ISSUE THREAD

**Issue by boyum** [boyum/markdown-it-image-size#416]
- [x] Replace `sync-fetch` with something that supports ESM

💡 Current solution: Import `markdown-it-image-size` with `require`, not `import`:

From:

```js
import { markdownItImageSize } from "markdown-it-image-size";
```

To:

```js
const { markdownItImageSize } = require("markdown-it-image-size");
```

---

Reporter: @dingshaohua-cn

i use it in my react project created base on vite， vite just support esm
```js
import {markdownItImageSize}  from 'markdown-it-image-size';
// console.log(111, markdownItImageSize);

const md = MarkdownIt({
  html: true,
  linkify: true,
  typographer: true,
}).use(markdownItImageSize);
/
```

and find this error
```
chunk-CEQRFMJQ.js?v=9d55e0d4:11 Module "util" has been externalized for browser compatibility. Cannot access "util.inherits" in client code. See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
get @ browser-external:util:9
(anonymous) @ index.js:128
node_modules/markdown-it-image-size/dist/index.js @ index.js:134
__require @ chunk-CEQRFMJQ.js?v=9d55e0d4:11
(anonymous) @ index.js:1526
chunk-CEQRFMJQ.js?v=9d55e0d4:11 Module "events" has been externalized for browser compatibility. Cannot access "events.EventEmitter" in client code. See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
get @ browser-external:events:9
node_modules/markdown-it-image-size/dist/index.js @ index.js:137
__require @ chunk-CEQRFMJQ.js?v=9d55e0d4:11
(anonymous) @ index.js:1526
index.js:147 Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at new Queue (index.js:147:16)
    at index.js:1321:17
    at node_modules/markdown-it-image-size/dist/index.js (index.js:1441:1)
    at __require (chunk-CEQRFMJQ.js?v=9d55e0d4:11:50)
    at index.js:1526:31
```

_Originally posted by @dingshaohua-cn in https://github.com/boyum/markdown-it-image-size/issues/402#issuecomment-1842491354_

**Comment by boyum** [comment]
`markdown-it-image-size` does currently not support ESM, because of how its dependencies `image-size` and `sync-fetch` work. Until that is fixed, you will have to either set `type` to `commonjs` instead of `module`, or import with `import()`. Using `import()` might pose a whole new set of problems, as MarkdownIt doesn't really support promises, but this might work:

```ts
import MarkdownIt from "markdown-it";

import("markdown-it-image-size").then(({ markdownItImageSize }) => {
  const md = MarkdownIt({
    html: true,
    linkify: true,
    typographer: true,
  }).use(markdownItImageSize);

  md.parse(
    `# Hello World ✨

![image](https://images.unsplash.com/photo-1577811037855-935237616bac?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2167&q=80 "title")`,
    {},
  );
});

```

**Comment by boyum** [comment]
Can you try using `require` instead of `import` when importing `markdown-it-image-size`?

From:

```js
import { markdownItImageSize } from "markdown-it-image-size";
```

To:

```js
const markdownItImageSize = require("markdown-it-image-size");
```
